## Calculation of Tensor

We treated `scalar` and we will talk about `tensor` like `vector` or `matrix`

In [2]:
import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.array(1.0))
y = F.sin(x)

print(y)

Variable(0.8414709848078965)


In [3]:
x = Variable(np.array([[1, 2, 3],
                       [4, 5, 6]]))
y = F.sin(x)

print(y)

Variable([[ 0.84147098  0.90929743  0.14112001]
          [-0.7568025  -0.95892427 -0.2794155 ]])


In [5]:
x = Variable(np.array([[1, 2, 3],
                       [4, 5, 6]]))
c = Variable(np.array([[10, 20, 30],
                       [40, 50, 60]]))

y = x + c

print(y)

Variable([[11 22 33]
          [44 55 66]])


Numpy `broadcast` function calculate tensor like scalar! But the shape should be the same :)!

## Backpropagation of Tensor

Backpropagation is made for `scalar`.<br>
But even its tensor, if we use `broadcast` the calculation is done by `scalar` by `scalar` so it works well :)

In [11]:
x = Variable(np.array([[1, 2, 3],
                       [4, 5, 6]]))
c = Variable(np.array([[10, 20, 30],
                       [40, 50, 60]]))

y = x + c
y.backward(retain_grad=True)

print(y.grad)
print(x.grad)
print(c.grad)

Variable([[1 1 1]
          [1 1 1]])
Variable([[1 1 1]
          [1 1 1]])
Variable([[1 1 1]
          [1 1 1]])
